name: Awesome approval workflow
on: pull_request_review

jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps:
      - name: Adding Approval Label
        uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "Approved!"
